package gov.hhs.cms.aca.global_assets.it.tests;

import static org.junit.Assert.assertNotNull;
import gov.hhs.cms.aca.global_assets.core.commons.SlingHelpersImpl;
import gov.hhs.cms.aca.global_assets.core.commons.Utils;
import gov.hhs.cms.aca.global_assets.core.models.documentservices.DocAssuranceServiceCaller;
import gov.hhs.cms.aca.global_assets.core.models.documentservices.OutputServiceCaller;

import java.io.IOException;
import java.util.Dictionary;

import javax.jcr.Session;

import org.apache.sling.api.resource.LoginException;
import org.apache.sling.api.resource.ResourceResolver;
import org.apache.sling.junit.annotations.SlingAnnotationsTestRunner;
import org.junit.Test;
import org.junit.runner.RunWith;

/**
 * The class <code>SlingHelpersImplTest</code> contains tests for the class
 * {@link <code>SlingHelpersImpl</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 25/03/16 11:36 AM
 *
 * @author Guillaume
 *
 * @version $Revision$
 */
/** 
 *  Test case which uses OSGi services injection
 *  to get hold of the Commons related classes which 
 *  it wants to test server-side. 
 */
@RunWith(SlingAnnotationsTestRunner.class)
public class SlingHelpersImplTest {


	/**
	 * Run the Object getAmbiguousService(Object, Class) method test
	 */
	@Test
	public void testGetAmbiguousService() {
		Object result = (OutputServiceCaller) SlingHelpersImpl.getAmbiguousService(this, OutputServiceCaller.class);
		assertNotNull(result);
	}

	/**
	 * Run the String getConfig(String, String) method test
	 * @throws IOException 
	 */
	@Test
	public void testGetConfig() throws IOException {
		// add test code here
		String pid = "gov.hhs.cms.aca.global_assets.core.models.documentservices.OutputServiceCallerImpl";
		String key = "gov.hhs.cms.aca.global_assets.core.models.documentservices.OutputServiceCallerImpl.TAGGED_PDF";
		
		Dictionary<?, ?> result2 = SlingHelpersImpl.getConfig(pid);
		assertNotNull("Testing getConfig(String)", result2);
		
		String result = SlingHelpersImpl.getConfig(pid, key);
		assertNotNull("Testing getConfig(String, String)", result);
	}

	/**
	 * Run the ResourceResolver getResourceResolver(Session) method test
	 * @throws LoginException 
	 */
	@Test
	public void testGetResourceResolver() throws LoginException {
		
		String serviceUserString = "aca-service";
		
		ResourceResolver result = SlingHelpersImpl.getResourceResolver(serviceUserString);
		assertNotNull("Testing getResourceResolver(String)", result);
		
		Session session = result.adaptTo(Session.class);
		
		ResourceResolver result2 = SlingHelpersImpl.getResourceResolver(session);
		assertNotNull("Testing getResourceResolver(Session session)", result2);
		
	}

	/**
	 * Run the String getServiceProperty(Object, String) method test
	 */
	//TODO Get a valid property to query
	public void testGetServiceProperty() {
		Object caller = Utils.class;
		String property = "Built-By";
		String result = SlingHelpersImpl.getServiceProperty(caller, property);
		assertNotNull(result);
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = getAmbiguousService(QObject;!QClass;),getConfig(QString;!QString;),getConfig(QString;),getResourceResolver(QSession;),getResourceResolver(QString;),getServiceProperty(QObject;!QString;)
 * package = gov.hhs.cms.aca.global_assets.it.tests
 * package.sourceFolder = global-assets.it.tests/src/main/java
 * superclassType = junit.framework.TestCase
 * testCase = SlingHelpersImplTest
 * testClassType = gov.hhs.cms.aca.global_assets.core.commons.SlingHelpersImpl
 */